import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import Main from "@/components/main";
import { Box, VStack } from "@chakra-ui/react";
import About from "@/components/about";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Janvi Bajoria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack>
        <Box
          bgColor={"black"}
          p={["4", "8", "16"]}
          minH={"100vh"}
          w={["100%", "90%", "70%"]}
        >
          <Navbar />
          <Main />
          <About />
        </Box>
      </VStack>
    </>
  );
}
